# Generated by Django 4.2.15 on 2024-08-20 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import switch.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('switch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalComputer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=50, verbose_name='Hostname')),
                ('dados', models.CharField(blank=True, choices=[('', 'seleciona rede de dados'), ('20', '20-Dados Administração'), ('15', '15-Dados Atendimento')], max_length=4, null=True)),
                ('voz', models.CharField(blank=True, choices=[('', 'seleciona rede de dados'), ('21', '20-voz Administração'), ('16', '15-voz Atendimento')], max_length=4, null=True)),
                ('porta', models.CharField(max_length=8, verbose_name='Porta Switch')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('switch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='switch.switch', verbose_name=switch.models.Switch)),
                ('usuarioa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical computer',
                'verbose_name_plural': 'historical computers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='Hostname')),
                ('dados', models.CharField(blank=True, choices=[('', 'seleciona rede de dados'), ('20', '20-Dados Administração'), ('15', '15-Dados Atendimento')], max_length=4, null=True)),
                ('voz', models.CharField(blank=True, choices=[('', 'seleciona rede de dados'), ('21', '20-voz Administração'), ('16', '15-voz Atendimento')], max_length=4, null=True)),
                ('porta', models.CharField(max_length=8, verbose_name='Porta Switch')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='switch.switch', verbose_name=switch.models.Switch)),
                ('usuarioa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
