# Generated by Django 4.2.15 on 2024-08-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='porta',
            field=models.CharField(choices=[('', 'selecione a porta'), ('1', 'Giga0/0'), ('2', 'Giga0/1'), ('3', 'Giga0/2'), ('4', 'Giga0/3'), ('5', 'giga0/4'), ('6', 'giga0/5'), ('7', 'Giga0/6'), ('8', 'Giga0/7')], max_length=8, verbose_name='Porta Switch'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='porta',
            field=models.CharField(choices=[('', 'selecione a porta'), ('1', 'Giga0/0'), ('2', 'Giga0/1'), ('3', 'Giga0/2'), ('4', 'Giga0/3'), ('5', 'giga0/4'), ('6', 'giga0/5'), ('7', 'Giga0/6'), ('8', 'Giga0/7')], max_length=8, verbose_name='Porta Switch'),
        ),
    ]
