# Generated by Django 4.2.15 on 2024-08-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0001_initial'),
        ('computador', '0002_alter_computer_porta_alter_historicalcomputer_porta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='switch.switch', verbose_name='Switch'),
        ),
        migrations.AlterField(
            model_name='historicalcomputer',
            name='switch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='switch.switch', verbose_name='Switch'),
        ),
    ]
